{"uuid": "fec72c95-4f38-4522-befd-e53105a95960", "children": ["6a39c874-c735-4ca4-8604-44f135d1cb8c"], "befores": [{"name": "compare", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=128.0.6613.114)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6E7DDB5D2+29090]\n\t(No symbol) [0x00007FF6E7D4E689]\n\t(No symbol) [0x00007FF6E7C0B1CA]\n\t(No symbol) [0x00007FF6E7BDFAF5]\n\t(No symbol) [0x00007FF6E7C8E2E7]\n\t(No symbol) [0x00007FF6E7CA5EE1]\n\t(No symbol) [0x00007FF6E7C86493]\n\t(No symbol) [0x00007FF6E7C509B1]\n\t(No symbol) [0x00007FF6E7C51B11]\n\tGetHandleVerifier [0x00007FF6E80F8C5D+3295277]\n\tGetHandleVerifier [0x00007FF6E8144843+3605523]\n\tGetHandleVerifier [0x00007FF6E813A707+3564247]\n\tGetHandleVerifier [0x00007FF6E7E96EB6+797318]\n\t(No symbol) [0x00007FF6E7D5980F]\n\t(No symbol) [0x00007FF6E7D553F4]\n\t(No symbol) [0x00007FF6E7D55580]\n\t(No symbol) [0x00007FF6E7D44A1F]\n\tBaseThreadInitThunk [0x00007FFE6BD76FD4+20]\n\tRtlUserThreadStart [0x00007FFE6C1BCF31+33]\n\n", "trace": "  File \"C:\\Python_Selenium\\Selenium\\Demo_Testcases\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Python_Selenium\\Selenium\\Demo_Testcases\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Python_Selenium\\Selenium\\Demo_Testcases\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python_Selenium\\Selenium\\Demo_Testcases\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python_Selenium\\Selenium\\Demo_Testcases\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Python_Selenium\\Selenium\\Demo_Testcases\\Tests\\conftest.py\", line 65, in compare\n    compare.maximize_window()\n  File \"C:\\Python_Selenium\\Selenium\\Demo_Testcases\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 506, in maximize_window\n    self.execute(command, None)\n  File \"C:\\Python_Selenium\\Selenium\\Demo_Testcases\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Python_Selenium\\Selenium\\Demo_Testcases\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1725461527940, "stop": 1725461532555}], "start": 1725461527940, "stop": 1725461533116}